# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd cms-api
    npm install
  displayName: 'npm install'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'kapp-cms-connection'
    regionName: 'ap-southeast-1'
    scriptType: 'inline'
    inlineScript: |
      # You can write your script inline here
      cd cms-api
      sls deploy -s dev