service: kapp-cms-api

plugins:
  - serverless-offline
  - serverless-mocha-plugin

provider:
  region: ap-southeast-1
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  versionFunctions: false
  environment: ${file(env.yml):${self:custom.stage}}
  timeout: 30

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  app:
    handler: src/app-serverless.handler
    events:
      - http: 
          path: /{proxy+}
          method: any
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:ap-southeast-1:${file(env.yml):${self:custom.stage}.AWS_ACCOUNT}:userpool/${file(env.yml):${self:custom.stage}.REGION}_${file(env.yml):${self:custom.stage}.COGNITO_POOL_ID}

  login:
    handler: src/app-serverless.handler
    events:
      - http:
          path: /login
          method: any
          cors: true