'use strict';

// tests for app
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('app', '/src/app-serverless.js', 'handler');

const {
  eventPostRequestBody 
} = require('./helpers');


describe('app', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async  () => {
    const body = {
      firstName:'John',
      lastName:'Doe'
    };
    const response = await wrapped.run(eventPostRequestBody(body));
    const {
      firstName,
      lastName
    } = JSON.parse(response.body);

    expect({
      firstName,
      lastName
    }).to.eql(body);
  
  });
});

