/* eslint-disable no-undef */

// tests for app
// Generated by serverless-mocha-plugin
const mochaPlugin = require('serverless-mocha-plugin');

const { expect } = mochaPlugin.chai;
const wrapped = mochaPlugin.getWrapper('app', '/src/app-serverless.js', 'handler');

// init adv data
let advData;

describe('Advisory', () => {
  before((done) => {
    done();
  });

  it('list advisory', async () => {
    const response = await wrapped.run({
      resource: '/api',
      path: '/api/advisories',
      httpMethod: 'GET',
      headers: {
        Accept: 'application/json',
        'content-type': 'application/json',
      },
    });

    const res = JSON.parse(response.body);
    expect(res).to.be.an('array');
  });
});
