'use strict';

// tests for app
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('app', '/src/app-serverless.js', 'handler');

const {
  eventPostRequest
} = require('./helpers');


describe('app', () => {
  before((done) => {
    done();
  });

  it('create user', async  () => {
    const body = {
      firstName:'John',
      lastName:'Doe'
    };
    const response = await wrapped.run(eventPostRequest({
      body: JSON.stringify(body),
      path: '/api/users',
      httpMethod: 'POST',
    }));
    const {
      firstName,
      lastName
    } = JSON.parse(response.body);

    expect({
      firstName,
      lastName
    }).to.eql(body);
  
  });

  it('create post', async  () => {
    const body = {
      data:{
        content:'The Quick brownfox jump over the lazy dog',
        attachments:'www.google.com/dog.pdf'
      },
    };

    const response = await wrapped.run(eventPostRequest({
      body: JSON.stringify(body),
      path: '/api/posts',
      httpMethod: 'POST',
    }));
  });
});

