'use strict';

// tests for app
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('app', '/src/app-serverless.js', 'handler');

const {
  eventPostRequest
} = require('../helpers');


describe('app', () => {
  before((done) => {
    done();
  });

  it('create post', async  () => {
    const response = await wrapped.run(
      { resource: '/login',
        path: '/login',
        httpMethod: 'POST',
        headers: 
   { Accept: 'application/json',
     'content-type': 'application/json' },
        body: '{"query":"mutation{login(credentials:{username:\\"41\\",password:\\"passord\\"}){accessToken accessTokenExpiresAt}}","variables":{},"operationName":null}' }
    );
    const {
      data:{
        login
      }
    } = JSON.parse(response.body);
    expect(login).to.have.property('accessToken');
    expect(login).to.have.property('accessTokenExpiresAt');
  });
});

