'use strict';

// tests for app
// Generated by serverless-mocha-plugin
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('app', '/src/app-serverless.js', 'handler');

// init post data
let postData;

describe('Post Crud', () => {
  before((done) => {
    done();
  });

  it('list post', async () => {
    const response = await wrapped.run({
      resource: '/graphql',
      path: '/graphql',
      httpMethod: 'POST',
      headers: {
        Accept: 'application/json',
        'content-type': 'application/json'
      },
      body: '{"query": "query{getPosts{id title content tags{id name}}}"}'
    });

    const {
      data: {
        getPosts
      }
    } = JSON.parse(response.body);

    expect(getPosts).to.be.an('array');
  });

  it('create post', async () => {
    const response = await wrapped.run({
      resource: '/graphql',
      path: '/graphql',
      httpMethod: 'POST',
      headers: {
        Accept: 'application/json',
        'content-type': 'application/json'
      },
      body: '{"query": "mutation{createPost(data:{userId:1 categoryId:1 subCategory:2 title:\\"Test Post\\" content:\\"Lorem ipsum dolor sit amet.\\" priorityLevel:\\"urgent\\" source:\\"https://news.abs-cbn.com\\" locationLat:\\"123\\" locationLong:\\"123\\" locationAddress:\\"Quezon City\\" draft:false scheduled:\\"2019-10-14T07:27:57+0000\\" expiration:\\"2019-10-14T07:27:57+0000\\" published:\\"2019-10-14T07:27:57+0000\\" tags:[{name:\\"sample post tag 1\\"},{name:\\"sample post tag 2\\"}]}){id title content tags{id name}}}"}'
    });

    const {
      data: {
        createPost
      }
    } = JSON.parse(response.body);

    // save post data for next test case
    postData = createPost;

    expect(createPost).to.be.an('object');
    expect(createPost).to.have.property('id');
  });

  it('show post', async () => {
    const response = await wrapped.run({
      resource: '/graphql',
      path: '/graphql',
      httpMethod: 'POST',
      headers: {
        Accept: 'application/json',
        'content-type': 'application/json'
      },
      body: `{"query":"query{getPost(where:{id:${postData.id}}){id title content tags{id name}}}"}`
    });

    const {
      data: {
        getPost
      }
    } = JSON.parse(response.body);

    expect(getPost).to.be.an('object');
    expect(getPost).to.have.property('title');
    expect(getPost.title).to.eql('Test Post');
  });
});